-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 14:44:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema certification_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema certification_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `certification_database` DEFAULT CHARACTER SET utf8 ;
USE `certification_database` ;

-- -----------------------------------------------------
-- Table `certification_database`.`Health_Facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Health_Facilities` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`faculty_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Specialists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Specialists` (
  `specialist_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `Health_Facilities_faculty_id` INT NULL,
  PRIMARY KEY (`specialist_id`),
  UNIQUE INDEX `specialist_id_UNIQUE` (`specialist_id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Specialists_Health_Facilities_idx` (`Health_Facilities_faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_Specialists_Health_Facilities`
    FOREIGN KEY (`Health_Facilities_faculty_id`)
    REFERENCES `certification_database`.`Health_Facilities` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Everyday_Unique_Passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Everyday_Unique_Passwords` (
  `date` DATE NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(100) NOT NULL,
  `qualification` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Certification_Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Certification_Tests` (
  `certification_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `result` TINYINT(3) NOT NULL,
  `Specialists_specialist_id` INT NOT NULL,
  `Courses_course_id` INT NOT NULL,
  PRIMARY KEY (`certification_id`),
  INDEX `fk_Sertification_Tests_Specialists1_idx` (`Specialists_specialist_id` ASC) VISIBLE,
  INDEX `fk_Sertification_Tests_Courses1_idx` (`Courses_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sertification_Tests_Specialists1`
    FOREIGN KEY (`Specialists_specialist_id`)
    REFERENCES `certification_database`.`Specialists` (`specialist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sertification_Tests_Courses1`
    FOREIGN KEY (`Courses_course_id`)
    REFERENCES `certification_database`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Topics` (
  `topic_id` INT NOT NULL,
  `topic_name` VARCHAR(100) NOT NULL,
  `count_of_questions` MEDIUMINT(3) NOT NULL,
  `Courses_course_id` INT NOT NULL,
  PRIMARY KEY (`topic_id`, `Courses_course_id`),
  INDEX `fk_Topics_Courses1_idx` (`Courses_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Topics_Courses1`
    FOREIGN KEY (`Courses_course_id`)
    REFERENCES `certification_database`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Training_Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Training_Tests` (
  `training_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `result` TINYINT(3) NULL,
  `Specialists_specialist_id` INT NOT NULL,
  `Topics_topic_id` INT NOT NULL,
  PRIMARY KEY (`training_id`),
  INDEX `fk_Training_Test_Specialists1_idx` (`Specialists_specialist_id` ASC) VISIBLE,
  INDEX `fk_Training_Test_Topics1_idx` (`Topics_topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_Training_Test_Specialists1`
    FOREIGN KEY (`Specialists_specialist_id`)
    REFERENCES `certification_database`.`Specialists` (`specialist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Training_Test_Topics1`
    FOREIGN KEY (`Topics_topic_id`)
    REFERENCES `certification_database`.`Topics` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certification_database`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certification_database`.`Questions` (
  `question_id` INT NOT NULL,
  `question` VARCHAR(100) NOT NULL,
  `answer_1` VARCHAR(100) NOT NULL,
  `is_answer_1_true` TINYINT NOT NULL,
  `answer_2` VARCHAR(100) NOT NULL,
  `is_answer_2_true` TINYINT NOT NULL,
  `answer_3` VARCHAR(100) NULL,
  `is_answer_3_true` TINYINT NULL,
  `answer_4` VARCHAR(100) NULL,
  `is_answer_4_true` TINYINT NULL,
  `answer_5` VARCHAR(100) NULL,
  `is_answer_5_true` TINYINT NULL,
  `Topics_topic_id` TINYINT NOT NULL,
  PRIMARY KEY (`question_id`, `Topics_topic_id`),
  INDEX `fk_Questions_Topics1_idx` (`Topics_topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Topics1`
    FOREIGN KEY (`Topics_topic_id`)
    REFERENCES `certification_database`.`Topics` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
